services:
  db:
    image: postgres:16.4-bookworm
    platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-directus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-directus}
      POSTGRES_DB: ${POSTGRES_DB:-directus}
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=${DB_USER:-directus}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  directus:
    image: directus/directus:11.5.1
    ports:
      - ${PORT:-8055}:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      # Database Config
      DB_CLIENT: "pg"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_DATABASE: ${POSTGRES_DB:-directus}
      DB_USER: ${POSTGRES_USER:-directus}
      DB_PASSWORD: ${DB_PASSWORD:-directus}

      # Directus Config
      KEY: ${DIRECTUS_KEY:-change-me}
      SECRET: ${DIRECTUS_SECRET:-change-me}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD:-directus}
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL:-http://localhost:8055}
      
      # could be nice in future
      WEBSOCKETS_ENABLED: "true"
      
      # Cache Config (using memory for simplicity)
      CACHE_ENABLED: "true"
      CACHE_STORE: "memory"
    depends_on:
      db:
        condition: service_healthy 